### ISSUE TITLE
Global attributes sometimes missing

### ISSUE THREAD

**Issue by ElodieFZ** [NasjonaltBakkeSegment/safe_to_netcdf#4]
For some products (ex S2A/2020/12/16/S2A_MSIL1C_20201216T105441_N0209_R051_T32VLK_20201216T130155.nc), most of the global attributes are missing.
I looked at S2A nc files from 2020. There are several files like that every month. So it's not a one time problem. 
It has happened to both 'normal' and 'dterreng' files.

I'm guessing the pb is at line 571 `ncout.setncatts(self.globalAttribs)` or somewhere there. The attributes present are the ones directly written to the nc file (like `ncout.title = 'Sentinel-2 L1C data'` for example). Whereas the ones written through `self.globalAttribs` are missing.

I 'investigated' the product S2B_MSIL1C_20201211T105349_N0209_R051_T33VUH_20201211T113840
When running it now with the wrapper, the output file has all the expected metadata.
So the problem must be linked to an external event happening in PPI at the same time. a conflict, an I/O error, a memory error? 

The plan now is to wait and get another error like that again and check in the logs what happened.

**Comment by hevgyrt** [comment]
In the case above, it seems likely to be related to the GDAL version? For [http://nbstds.met.no/thredds/dodsC/NBS/S2A/2020/12/16/S2A_MSIL1C_20201216T105441_N0209_R051_T32VLK_20201216T130155.nc.html](http://nbstds.met.no/thredds/dodsC/NBS/S2A/2020/12/16/S2A_MSIL1C_20201216T105441_N0209_R051_T32VLK_20201216T130155.nc), only three global attributes made it.

**Comment by ElodieFZ** [comment]
Closing the issue as the problem has not been observed in more than a year.
Re-open if necessary.
